name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
      COGNITO_USERPOOL_ID: ${{ secrets.COGNITO_USERPOOL_ID }}
      COGNITO_APP_CLIENT_ID: ${{ secrets.COGNITO_APP_CLIENT_ID }}
    strategy:
      matrix:
        # Quote versions so YAML doesn't parse them as floats (3.10 -> 3.1)
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load .env into job environment
        run: |
          if [ -f .env ]; then
            while IFS= read -r line || [ -n "$line" ]; do
              # skip empty lines and comments
              if [[ -z "$line" || "$line" == \#* ]]; then
                continue
              fi
              echo "$line" >> $GITHUB_ENV
            done < .env
          fi

      - name: Check env vars exist
        run: |
          echo "COGNITO_REGION set: ${COGNITO_REGION:+yes}"
          echo "COGNITO_USERPOOL_ID set: ${COGNITO_USERPOOL_ID:+yes}"
          echo "COGNITO_APP_CLIENT_ID set: ${COGNITO_APP_CLIENT_ID:+yes}"

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q
